<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "roq_redirect"
 *
 * Auto generated by Extension Builder 2013-10-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Redirect',
	'description' => 'Manage redirects in the backend of TYPO3. You can use this for multidomain sites and with multiple translations.',
	'category' => 'plugin',
	'author' => 'Patrick Wiggelman',
	'author_email' => 'extensions@roquin.nl',
	'author_company' => 'ROQUIN B.V.',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>